### PR TITLE
Django 1.8 compatibility changes

### PR DESCRIPTION
**Pull request by gabber7**

### CODE REVIEW

**Comment by gabber7** [comment]
hi fitzgen, can you please publish a new package on pypi if the patch is ok for you? thx

**Comment by fitzgen** [comment]
Hi @gabber7, do you want to be maintainer of this package? I haven't used it or hacked on it for a long time and have no plans to touch it again in the future.

**Comment by gabber7** [comment]
Hi @fitzgen, sure, why not. Though I'm not  experienced in maintaining
packages, this project is maybe a good start to learn that. Greetings.

2015-11-13 17:29 GMT+01:00 Nick Fitzgerald notifications@github.com:

**Comment by fitzgen** [comment]
Cool! What is your pypi username so I can add you as an owner?

_Nick_

**Comment by gabber7** [comment]
gabber7, thx
Am 14.11.2015 5:06 nachm. schrieb "Nick Fitzgerald" <
notifications@github.com>:

**Comment by fitzgen** [comment]
Added! Good luck :)

_Nick_

**Pull request merged**
